#!/bin/bash
echo "Enter a number: "
read number
if [ $number -le 1 ]; then
  echo "$number is not prime."
else
  is_prime=true
  for (( i=2; i<$number; i++ ))
  do
    if [ $((number % i)) -eq 0 ]; then
      is_prime=false
      break
    fi
  done
if [ $is_prime == true ]; then
    echo "$number is prime."
  else
    echo "$number is not prime."
  fi
fi
